# BATCH_DS2310_PHASE3_EVALUATION_PROJECT2

## Data Exploration and Loading

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("weatherAUS.csv")

In [5]:
df.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RainTomorrow  
0            No  
1            No  
2            No  
3            No  
4            No  

[5 rows x 23 columns]

## Data Preprocessing

In [6]:
import numpy as np
import pandas as pd 


In [7]:
X =df.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y=df.iloc[:,-1].values

In [8]:
X

array([['Albury', 13.4, 22.9, ..., 16.9, 21.8, 'No'],
       ['Albury', 7.4, 25.1, ..., 17.2, 24.3, 'No'],
       ['Albury', 12.9, 25.7, ..., 21.0, 23.2, 'No'],
       ...,
       ['Uluru', 5.4, 26.9, ..., 12.5, 26.1, 'No'],
       ['Uluru', 7.8, 27.0, ..., 15.1, 26.0, 'No'],
       ['Uluru', 14.9, nan, ..., 15.0, 20.9, 'No']], dtype=object)

In [9]:
Y=Y.reshape(-1,1)


In [10]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X=imputer.fit_transform(X)
Y=imputer.fit_transform(Y)

In [11]:
X

array([['Albury', 13.4, 22.9, ..., 16.9, 21.8, 'No'],
       ['Albury', 7.4, 25.1, ..., 17.2, 24.3, 'No'],
       ['Albury', 12.9, 25.7, ..., 21.0, 23.2, 'No'],
       ...,
       ['Uluru', 5.4, 26.9, ..., 12.5, 26.1, 'No'],
       ['Uluru', 7.8, 27.0, ..., 15.1, 26.0, 'No'],
       ['Uluru', 14.9, 19.0, ..., 15.0, 20.9, 'No']], dtype=object)

In [12]:
Y

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
X[:,0]=le1.fit_transform(X[:,0])
X[:,4]=le1.fit_transform(X[:,4])
X[:,6]=le1.fit_transform(X[:,6])
X[:,7]=le1.fit_transform(X[:,7])
X[:,-1]=le1.fit_transform(X[:,-1])

In [14]:
Y=le1.fit_transform(Y)

C:\Users\Debanjan\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
X

array([[1, 13.4, 22.9, ..., 16.9, 21.8, 0],
       [1, 7.4, 25.1, ..., 17.2, 24.3, 0],
       [1, 12.9, 25.7, ..., 21.0, 23.2, 0],
       ...,
       [9, 5.4, 26.9, ..., 12.5, 26.1, 0],
       [9, 7.8, 27.0, ..., 15.1, 26.0, 0],
       [9, 14.9, 19.0, ..., 15.0, 20.9, 0]], dtype=object)

In [16]:
Y

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [18]:
X

array([[-1.51577598,  0.04039106, -0.15101108, ..., -0.15006358,
        -0.10175254, -0.55609919],
       [-1.51577598, -1.07478085,  0.20800875, ..., -0.09661746,
         0.318031  , -0.55609919],
       [-1.51577598, -0.05253993,  0.30592325, ...,  0.58036664,
         0.13332624, -0.55609919],
       ...,
       [ 1.01389522, -1.44650482,  0.50175225, ..., -0.93393991,
         0.62027515, -0.55609919],
       [ 1.01389522, -1.00043606,  0.51807133, ..., -0.47074026,
         0.60348381, -0.55609919],
       [ 1.01389522,  0.31918404, -0.78745533, ..., -0.48855563,
        -0.25287462, -0.55609919]])

## Splitting Data for model Trainning

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=81)

In [20]:
X_train

array([[-1.51577598,  0.05897726, -0.15101108, ...,  0.04590551,
        -0.15212657,  1.79824035],
       [ 0.38147742,  0.95111479, -0.00413933, ...,  0.40221293,
         0.01578685,  1.79824035],
       [ 0.69768632,  0.52363223,  1.17083466, ...,  0.90104333,
         1.40946822, -0.55609919],
       ...,
       [ 1.64631302,  1.11839058, -0.00413933, ...,  0.52692053,
         0.15011758, -0.55609919],
       [ 1.33010412,  0.96970099,  0.37119958, ...,  0.6694435 ,
         0.38519637,  1.79824035],
       [ 0.69768632,  1.37859736,  2.42740407, ...,  1.57802744,
         2.68561019, -0.55609919]])

In [21]:
Y_train

array([1, 0, 0, ..., 0, 1, 0])

## Building Model 

In [22]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=81)

In [23]:
classifier.fit(X_train,Y_train)

RandomForestClassifier(random_state=81)

In [24]:
classifier.score(X_train,Y_train)

0.9998516320474777

In [25]:
y_pred=classifier.predict(X_test)

In [26]:
y_pred

array([0, 1, 0, ..., 0, 0, 1])

In [27]:
y_pred=le1.inverse_transform(y_pred)

In [28]:
y_pred

array(['No', 'Yes', 'No', ..., 'No', 'No', 'Yes'], dtype=object)

In [29]:
Y_test

array([0, 1, 0, ..., 0, 0, 1])

In [30]:
Y_test=le1.inverse_transform(Y_test)

In [31]:
Y_test

array(['No', 'Yes', 'No', ..., 'No', 'No', 'Yes'], dtype=object)

In [32]:
Y_test=Y_test.reshape(-1,1)
y_pred = y_pred.reshape(-1,1)

In [33]:
data=np.concatenate((Y_test,y_pred),axis=1)
data1=pd.DataFrame(data,columns=['Rain in Tomorrow','Prediction of Rain'])

In [34]:
data1

Rain in Tomorrow Prediction of Rain
0                  No                 No
1                 Yes                Yes
2                  No                 No
3                 Yes                 No
4                  No                 No
...               ...                ...
1680               No                 No
1681               No                 No
1682               No                 No
1683               No                 No
1684              Yes                Yes

[1685 rows x 2 columns]

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.914540059347181

In [36]:
from xgboost import XGBClassifier

classifier = XGBClassifier(n_estimators=100, random_state=81)

classifier.fit(X_train,Y_train)
print(classifier.score(X_train,Y_train))
y_pred=classifier.predict(X_test)
print(y_pred)
y_pred=le1.inverse_transform(y_pred)
print(y_pred)

0.9951038575667656
[0 1 0 ... 0 0 1]
['No' 'Yes' 'No' ... 'No' 'No' 'Yes']


In [37]:
Y_test

array([['No'],
       ['Yes'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['Yes']], dtype=object)

In [38]:
y_pred = y_pred.reshape(-1,1)
data=np.concatenate((Y_test,y_pred),axis=1)
data1=pd.DataFrame(data,columns=['Rain in Tomorrow','Prediction of Rain'])

In [39]:
data1

Rain in Tomorrow Prediction of Rain
0                  No                 No
1                 Yes                Yes
2                  No                 No
3                 Yes                Yes
4                  No                 No
...               ...                ...
1680               No                 No
1681               No                 No
1682               No                 No
1683               No                 No
1684              Yes                Yes

[1685 rows x 2 columns]

## Choosing and Saving Best Model

In [40]:
best_model=XGBClassifier()

In [41]:
from joblib import dump
dump(best_model, 'best_model_Rain_Prediction.joblib')
print("Best model saved successfully.")

Best model saved successfully.


## findings:

* It is very much possible to train almost perfect model to predict rainfall for tomorrow of any given time
* **XGBClassifier()** is best model because of effectively model nonlinear relationships,incorporate feature importance etc.